
#######
GET http://localhost:8080/job/1

###

POST http://localhost:8080/job
Content-Type: application/json

{
    "title": "Software developer",
    "description": "8 hr workdays, a year at least",
    "employer": "Adobe",
    "salary": 5000,
    "location": "San Francisco",
    "abilities": ["Java", "C"],
    "domains": ["SWE"],
    "characteristics": ["paid leave", "benefits"]
}

#### Example job 3
POST http://localhost:8080/job
Content-Type: application/json

{
    "title": "QA Engineer",
    "description": "part-time contract",
    "employer": "Amazon",
    "salary": 10000,
    "location": "London",
    "abilities": ["DevOps", "Agile"],
    "domains": ["Testing", "Development", "Delivery", "DevOps"],
    "characteristics": ["hybrid"]
}
#===================================================
#### Create User
### Create a user
@postUsername = bagsylina
@postPassword = Parola1#
@postEmail = fabian@bagsylina.com
POST http://localhost:8080/user
Content-Type: application/json

{
    "username": "{{postUsername}}",
    "password": "{{postPassword}}",
    "email": "{{postEmail}}"
}

### Update a user
@putFirstName = Fabian
@putLastName = Anghel
PUT http://localhost:8080/user/bagsylina
Content-Type: application/json

{
    "firstName": "{{putFirstName}}",
    "lastName": "{{putLastName}}"
}

### Update user birthdate
@putBirthdate = 2003-04-02
PUT http://localhost:8080/user/bagsylina
Content-Type: application/json

{
    "birthdate": "{{putBirthdate}}"
}

### Update credentials
@putEmail = bagsylina@fabian.com
PUT http://localhost:8080/user-cred/bagsylina
Content-Type: application/json

{
    "email": "{{putEmail}}"
}

#===================================================
### Add a CV
@postCVDesc = test
@postCVAchieve = test
POST http://localhost:8080/user-cvs/bagsylina
Content-Type: application/json

{
    "description": "{{postCVDesc}}",
    "achievements": "{{postCVAchieve}}"
}


### Update CV
@putCVDesc = test2
PUT http://localhost:8080/cv/1
Content-Type: application/json

{
    "description": "{{putCVDesc}}"
}

### Add education
PUT http://localhost:8080/cv-add-exp/1
Content-Type: application/json

{
    "field": "education",
    "startDate": "2022-10-01",
    "title": "Bachelor of Computer Science",
    "institution": "University of Bucharest"
}


### Add a tag
PUT http://localhost:8080/cv-add-tag/1?field=language&tag=english

### Add a skills tab
PUT http://localhost:8080/cv-add-tag/1?field=skill&tag=Java

### Add another skills tab
PUT http://localhost:8080/cv-add-tag/1?field=skill&tag=C

### Add a tool tab
PUT http://localhost:8080/cv-add-tag/1?field=tool&tag=SWE

#===================================================


### Apply to job
POST http://localhost:8080/job-app/1?cvId=1

### Get all job applications for a job
GET http://localhost:8080/job-app/1

### Get all job applications for a user
GET http://localhost:8080/user-app/bagsylina

### Get job application
GET http://localhost:8080/app/1

### Delete job application
DELETE http://localhost:8080/app/1



### Get all applications to a job
GET http://localhost:8080/app/job/1

### Get all applications of a user
GET http://localhost:8080/app/user/1



### CHECK MATCH
GET http://localhost:8080/app/match/1?cvId=1

###
GET http://localhost:8080/app/recommend/1