pipeline {
    agent any
    tools {
        jdk 'jdk21'
    }

    environment {
        DOCKER_PASSWORD = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Tag image') {
            steps {
                script {
                    LATEST_TAG = sh(script: "git fetch --tags && git tag --sort=-creatordate | head -n 1", returnStdout: true).trim()
                    echo "Latest tag: ${LATEST_TAG}"

                    def (major, minor, patch) = LATEST_TAG.tokenize('.')
                    MAJOR_VERSION = major
                    MINOR_VERSION = minor
                    PATCH_VERSION = patch
                }
                sh "docker build -t anastasiastefanescu1618/careerquest2-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
            }
        }
    }
}
